default:
  email: "jj.espinoza.la@gmail.com"
  region: "us-west-1"

prod:
  bucket: "prod-linkedin-bot"
  step_function: "arn:aws:states:us-west-1:128472059203:stateMachine:linkedin-bot"

dev:
  bucket: "dev-linkedin-bot"
  step_function: "arn:aws:states:us-west-1:128472059203:stateMachine:dev-linkedin-bot"


min_salary: 0
min_similarity: 0

positions:
  - "Director Machine Learning"
  - "Vice President Machine Learning"
  - "Manager Machine Learning"
  - "Principal Machine Learning"
  - "Director Data Science"
  - "Vice President Data Science"
  - "Manager Data Science"
  - "Principal Data Science"
  - "Director Artificial Intelligence"
  - "Vice President Artificial Intelligence"
  - "Manager Artificial Intelligence"
  - "Principal Artificial Intelligence"
  - "Director Data Analytics"
  - "Vice President of Data Analytics"
  - "Manager of Data Analytics"
  - "Principal of Data Analytics"

locations:
  - "remote"

