default:
  email: "jj.espinoza.la@gmail.com"
  region: "us-west-1"

prod:
  bucket: "prod-linkedin-bot"
  step_function: "arn:aws:states:us-west-1:128472059203:stateMachine:linkedin-bot"

dev:
  bucket: "dev-linkedin-bot"
  step_function: "arn:aws:states:us-west-1:128472059203:stateMachine:dev-linkedin-bot"


min_salary: 0
min_similarity: 0

positions:
  - "Principal Machine Learning"
  - "Date Scientist"
  - "Machine Learning Engineer"
  - "AI/ML Architect"
  - "AI/ML Developer"
  - "Principal Machine Learning Engineer"
  - "Senior Data Scientist"
  - "Lead Data Scientist"
  - "Machine Learning Operations Engineer"

locations:
  - "remote"

